name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  current_date:
    runs-on: ubuntu-24.04
    steps:
      - name: Current date
        run: |
          date
  list_contents:
    runs-on: ubuntu-24.04
    steps:
      - name: Directory contents
        run: |
          ls -l
